top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY = CsOraStore

APPL_SRCS = \
CsDst_04.cc \
CsDstObject.cc \
CsFileRun.cc \
CsFileStore.cc \
CsOraRun.cc \
CsOraSession.cc \
CsOraStore.cc \
CsStoreMisc.cc \
FlatFile.cc \
PatchEventHeaderDB.cc \
RunInfo.cc

include $(top_srcdir)/makefiles/General.mk

