top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsHist
#VERBOSE = true

HEAD_EXT  = h

SRCS      = CsHistograms.$(SRC_EXT)     \
            CsHist.$(SRC_EXT)           \
            CsNtuple.$(SRC_EXT)

APPL_SRCS = $(SRCS) 

# General... do not remove...
include $(top_srcdir)/makefiles/General.mk

all: $(OS)/$(OBJ_ROOT)


