top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsSfDb

##### Add *.ddl file #######
SCHEMA_DDL =

APPL_SRCS = CsScifiDbUpdater.$(SRC_EXT)

include $(top_srcdir)/makefiles/General.mk
