/* XPM */
const char *compass_xpm[] = {
/* columns rows colors chars-per-pixel */
"125 124 8 1",
"  c Gray0",
". c #0084ff",
"X c #e80000",
"o c #0000f9",
"O c Gray100",
"+ c #f90000",
"@ c #f30000",
"# c Gray0",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooooO@@@OooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOOooooooOO@@OOooooooOOoooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooooOOOOOOOOO.O@@O.OOOOOOOOOooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOOO.OO........O@O.......O..OOOooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOOoOOO.....O........O@O.............OOOoOOoooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOOOO.................OO.................OOOOooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOO..O...................O.....................OOoooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOO................................................OOooO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOOoO....................................................OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOOO......................................................OOooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOOOO.......................................................OOOoooOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOooOO..............................................................OOoooOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOoooO..................................................................OoooOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOooO....................................................................OooOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOO@OO......................................................................OOO@OOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOooOO........................................................................OoooOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOooooOOO.........................................................................OOooooOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOooO..............................................................................OoooOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOooO................................................................................OooOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOooO..................................................................................OooOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOoO....................................................................................Oo@OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOoO....................................................................................OoOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOooOO......................................................................................OOooOOOOOOOOOOOOOOO",
"OOOOOOOOOO      oo .........      .......      .........      ..          ............. .............    O.  oOOOOOO    OO  O",
"OOOOOOO    OOOO    .......   ...   ........    .........    ......    ..    ........... ...........   .XO.   ooOOO   OOOO   O",
"OOOOOO    OOOOoo   ......   .....   .......    ........     ......    ...    .........   ..........  OXO..  .OooOO  OOOOO  OO",
"OOOOO    OOOOoooO ......   ......    ......    .......      ......   ....    ........    .........   XO.... ..Ooo   OOOOOO OO",
"OOOO    OOOOOooO. .....   .......    ..... .   ....... .   ......    ....    ........    .........   O..... ..Ooo   OOOOOO OO",
"OOOO    OOOOooO.. ....    .......    ..... .   ...... .    ......    ....    ....... .   .......OO    .........Oo    OOOOOOOO",
"OOO    OOOOOOOO.......    .......    ..... .   .....  .    ......    ....    ....... .   ......O+X     ........OO     OOOOOOO",
"OOO    OOOOOOOO......    ........    .... ..    .... ..   .......   ....    ....... ..   ....OO+XXO     .......OOO     OOOOOO",
"OO     OOOOooO.......    .......     .... ..    ... ...   ......    ...    ....... ...    ..O++XXO..     .......Ooo     OOOOO",
"OO    OOOOooO.......     .......     .... ..    ..  ..    ......         ......... ...    OO++XXO....     .......Ooo     OOOO",
"OO    OOOOooO.......    ........    ..... ..    .. ...    ......    ............. ....    +++XXO......    .......OooO    OOOO",
"OO    OOOooO........    ........    .... ...    . ....   .......   ..............         +XXXXO.......    .......OooO    OOO",
"OO    OOOooO........    .......    ..... ....   . ....   ......    ............. .....O   XXXXO........    .......Oooo    OOO",
"OO    OOooO.........    .......    ..... ....    ....    ......    ............  ...OO+   XXXO.. .......   .... ...OooO   OOO",
"OOO   OOooO.... ....    ......    ..... .....   .....    ......    ............ ..OO+++    XO... .......   .... ...OooO   OOO",
"OOO    OOO.... ......   ......   ...... .....   .....   .......   ............  .O+++++    O....  ......   ....  ...OOO   OOO",
"OOOO    OOO.  .......   .....   ......  .....  .....    ......    ...........   O+++++X    ....   ......  ....   ...OOO  OOOO",
"OOOOOO      ..........   ...   ......      .. ....        ..        ........     +++X        ..    ....  .....    ..Oo  OOOOO",
"OOOOOOOoO...............     ...............................................OO+++++XXXXXO...... ...     ...... ...     OOOOOO",
"OOOOOOooO..................................................................O++++++XXXXXO.............................OooOOOOO",
"OOOOOOooO................................................................OO++++++XXXXXO..............................OooOOOOO",
"OOOOOOoO................................................................O+++++++XXXXXO................................OoOOOOO",
"OOOOOooO..............................................................OO+++++++XXXXXO.................................OooOOOO",
"OOOOOooO............................................................OO+++++++XXXXXXO..................................OooOOOO",
"OOOOOooO...........................................................O++++++++XXXXXXXO..................................OoOOOOO",
"OOOOOOOO.........................................................OO++++++++XXXXXXXO...................................OO@OOOO",
"OOOOOOOO........................................................O+++++++++XXXXXXXO.....................................OOOOOO",
"OOOOOoO.......................................................OO+++++++++XXXXXXXO......................................OoOOOO",
"OOOOOoO......................................................O+++++++++XXXXXXXXO.......................................OoOOOO",
"OOOOooO....................................................OO+++++++++XXXXXXXXO........................................OooOOO",
"OOOOooO...................................................OO+++++++++XXXXXXXXO.........................................OooOOO",
"OOOOooO..................................................OXO++++++++XXXXXXXXO..........................................OooOOO",
"OOOOooO.................................................OXXXO++++++XXXXXXXXO...........................................OooOOO",
"OOOOooO................................................OXXXXXO++++XXXXXXXXO............................................OooOOO",
"OOOOOOO...............................................OXXXXXXXO+XXXXXXXXXO.............................................OOOOOO",
"OO@@@@@OOO...........................................OXXXXXXXXXOXXXXXXXXO..........................................OOOO@@@@@O",
"@@@@@@@@@OO.........................................OXXXXXXXXX+OXXXXXXXO...........................................OO@@@@@@@@",
"OOOO@OOOO..........................................OXXXXXXXXX+++OXXXXXO..............................................OOOO@OOO",
"OOOOOoO...........................................OXXXXXXXXX+++++OXXXXO................................................OoOOOO",
"OOOOooO...........................................OXXXXXXXX++++++OXXXO.................................................OooOOO",
"OOOOooO..........................................OXXXXXXXX++++++++OXO..................................................OooOOO",
"OOOOooO.........................................OXXXXXXX++++++++++OX...................................................OooOOO",
"OOOOooO........................................OXXXXXXX++++++++++O.....................................................OooOOO",
"OOOOOoO.......................................OXXXXXXX+++++++++OO......................................................OoOOOO",
"OOOOOoO......................................OXXXXXXX+++++++++O........................................................OoOOOO",
"OOOOOOOO....................................OXXXXXXX++++++++OO........................................................OOOOOOO",
"OOOOOOOO...................................OXXXXXX++++++++OO..........................................................OOOOOOO",
"OOOOOooO..................................OXXXXXX++++++++O............................................................OooOOOO",
"OOOOOooO.................................OXXXXXX+++++++OO.............................................................OooOOOO",
"OOOOOOoO................................OXXXXXX+++++++O...............................................................OoOOOOO",
"OOOOOOooO..............................OXXXXXX++++++OO...............................................................OooOOOOO",
"OOOOOOooO.............................OXXXXXX++++++O.................................................................OooOOOOO",
"OOOOOOooO............................OXXXXX++++++OO..................................................................OooOOOOO",
"OOOOOOOooO...........................OXXXX++++++O...................................................................OooOOOOOO",
"OOOOOOOooO..........................OXXXX+++++OO....................................................................OooOOOOOO",
"OOOOOOOOOOO........................OXXXX++++OO......................................................................OOOOOOOOO",
"OOOOOOOOOO........................OXXXX++++O........................................................................OOOOOOOOO",
"OOOOOOOOooO......................OXXXX+++OO........................................................................OooOOOOOOO",
"OOOOOOOOooO.....................OXXX++++O..........................................................................OooOOOOOOO",
"OOOOOOOOOooO...................OXXX+++OO..........................................................................OooOOOOOOOO",
"OOOOOOOOOooO..................OXXX+++O............................................................................OooOOOOOOOO",
"OOOOOOOOOOooO................OXXX++OO............................................................................OooOOOOOOOOO",
"OOOOOOOOOOooO...............OXXX++O..............................................................................OooOOOOOOOOO",
"OOOOOOOOOOOooOO............OXXX+OO..............................................................................OooOOOOOOOOOO",
"OOOOOOOOOOOoOO............OXX+OO...............................................................................OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOoO..........OXX+O.................................................................................OoO@OOOOOOOOOO",
"OOOOOOOOOOOOOooO.........OXOO.................................................................................OoooOOOOOOOOOOO",
"OOOOOOOOOOOOOooO........OXO...................................................................................OooOOOOOOOOOOOO",
"OOOOOOOOOOOOOOooO......OXO...................................................................................OooOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOoooO....OO....................................................................................OoooOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOooO...OO.....................................................................................OooOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOooO.O......................................................................................OooOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOoOO......................................................................................OOoOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO@OO....................................................................................OoOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOooO..................................................................................OooOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOoooO................................................................................OoooOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOoooO..............................................................................OoooOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOoooO............................................................................OoooOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOoooO..........................................................................OoooOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOooOO........................................................................OoooOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOO@OO......................................................................OOOoOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOooOO..................................................................OOooOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOoooO................................................................OoooOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOoooOO............................................................OOoooOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOO........................................................OOooooOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooOOO......................................................OOoooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOO..................................................OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOO..............................................OOoooO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOOOO..................OO..................OOOOooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooOOOO................OO................OOOoooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooOOooOOO....O........O@O............OOOooOOooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooOOOOO........O@O.......OOOOOoooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooOOOOOOOOOO@@OOOOOOOOOOoooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooOOoooooooO@@OoooooooOOooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooO@@@OoooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
