top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsUtils

APPL_SRCS = CsErrLog.$(SRC_EXT)       \
	    CsOpt.$(SRC_EXT)          \
            CsTime.$(SRC_EXT)         \
            CsRegistry.$(SRC_EXT)     \
            CsRegistrySing.$(SRC_EXT) \
	    CsStopwatch.$(SRC_EXT)    \
	    CsTimer.$(SRC_EXT)        \
	    CsRandom.$(SRC_EXT)       \
	    CsResource.$(SRC_EXT)     \
            ObjectsCounter.$(SRC_EXT)       	

include $(top_srcdir)/makefiles/General.mk
