top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsEvmc
TEST_PROGRAMS=

APPL_SRCS = CsGeant3.$(SRC_EXT)     \
	    CsMCHit.$(SRC_EXT)      \
	    CsMCTrkHit.$(SRC_EXT)   \
	    CsMCRICH1Hit.$(SRC_EXT)   \
	    CsMCParticle.$(SRC_EXT) \
	    CsMCTrack.$(SRC_EXT)    \
	    CsMCVertex.$(SRC_EXT)   \
	    CsMCUtils.$(SRC_EXT)    \
	    CsTmpTrigger.$(SRC_EXT) \

include $(top_srcdir)/makefiles/General.mk

