top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsTrigHod
TEST_PROGRAMS=

APPL_SRCS = \
CsTrigHodConstants.$(SRC_EXT) \
CsTrigHodDbUpdater.$(SRC_EXT) \
CsTrigHodDbReader.$(SRC_EXT) \

include $(top_srcdir)/makefiles/General.mk
