top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsECAL1DB
TEST_PROGRAMS=

##### Add *.ddl file #######
SCHEMA_DDL = 


APPL_SRCS = \
CsECAL1constants.$(SRC_EXT) \
CsECAL1DbReader.$(SRC_EXT) \
CsECAL1DbUpdater.$(SRC_EXT) \

include $(top_srcdir)/makefiles/General.mk
