top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsSpacePoint
TEST_PROGRAMS=

APPL_SRCS = CsDetFamily.$(SRC_EXT) \
            CsSPMaker.$(SRC_EXT) \
            CsSPUtils.$(SRC_EXT) \
            CsSpacePoint.$(SRC_EXT) \
            CsCalSpacePoint.$(SRC_EXT) \
            CsResOpt.$(SRC_EXT)

include $(top_srcdir)/makefiles/General.mk

