top_srcdir=../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsG3CallFile

#TEST_PROGRAMS=testG3CallFile

APPL_SRCS = \
        CsG3CallFile.$(SRC_EXT)		\
        CsMaterial.$(SRC_EXT)		\
        Gsdet.$(SRC_EXT)		\
        Gspos.$(SRC_EXT)		\
        Gstmed.$(SRC_EXT)		\
        Gsvolu.$(SRC_EXT)		\

include  ${top_srcdir}/makefiles/General.mk
