top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=VrtKalman

APPL_SRCS = getPatterns.$(SRC_EXT)     \
	    utils.$(SRC_EXT)           \
	    FindSecondaries.$(SRC_EXT) \
            FindPrimary.$(SRC_EXT)     \
	    doFitting.$(SRC_EXT)       \
	    doPattern.$(SRC_EXT)       \
	    CsAverPattern.$(SRC_EXT)   \
	    CsKalmanFitting.$(SRC_EXT) \
            CsVTrack.$(SRC_EXT)        \
	    Kalman.$(SRC_EXT)          \
            Pulls.$(SRC_EXT)          

include $(top_srcdir)/makefiles/General.mk

FDIRS=.
