top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsTrack
TEST_PROGRAMS=

APPL_SRCS = CsTrack.$(SRC_EXT)  \
	    CsHelix.$(SRC_EXT)  

include $(top_srcdir)/makefiles/General.mk

C_INCLUDES+=-I./traffic/includes
