top_srcdir = ../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY = CsRich1
TEST_PROGRAMS =

APPL_SRCS = CsRCUty.$(SRC_EXT) \
            CsRCCathode.$(SRC_EXT) \
            CsRCDetectors.$(SRC_EXT) \
            CsRCPhotonDet.$(SRC_EXT) \
            CsRCMirrors.$(SRC_EXT) \
            CsRCMirrorNom.$(SRC_EXT) \
            CsRCMirrorElem.$(SRC_EXT) \
            CsRCHistos.$(SRC_EXT) \
            CsRCEventParticles.$(SRC_EXT) \
            CsRCParticle.$(SRC_EXT) \
            CsRCEventPads.$(SRC_EXT) \
            CsRCPad.$(SRC_EXT) \
            CsRCEventClusters.$(SRC_EXT) \
            CsRCCluster.$(SRC_EXT) \
            CsRCEventPartPhotons.$(SRC_EXT) \
            CsRCPartPhotons.$(SRC_EXT) \
            CsRCPhoton.$(SRC_EXT) \
            CsRCEventRings.$(SRC_EXT) \
            CsRCRing.$(SRC_EXT) \
            CsRCEventAnalysis.$(SRC_EXT) \
	    CsRCEventDisplay.$(SRC_EXT) \
            CsRCExeKeys.$(SRC_EXT) \
            CsRCRecConst.$(SRC_EXT) \
	    CsRichOne.$(SRC_EXT) \
	    CsRCChiSqFit.$(SRC_EXT) \
            CsRCCircleFit.$(SRC_EXT) \
            CsRCEllipseFit.$(SRC_EXT) \
            CsRCEllipseFitTest.$(SRC_EXT) \
            CsRCGauPolFit.$(SRC_EXT) \
            CsRCnTup.$(SRC_EXT) \
	    CsRCLikeAll.$(SRC_EXT) \
	    CsRCLikeAll02.$(SRC_EXT) \
	    CsRCLikeAll03.$(SRC_EXT) \
	    CsRCLikeAll04.$(SRC_EXT) \
	    CsRCLikeAll05.$(SRC_EXT) \
	    CsRCLikeAllMap.$(SRC_EXT) \
	    CsRCLikeRing.$(SRC_EXT) \
	    CsRCLikeRing02.$(SRC_EXT) \
	    CsRCLikeRing03.$(SRC_EXT) \
	    CsRCLikeRing04.$(SRC_EXT) \
	    CsRCLikeRing05.$(SRC_EXT) \
	    CsRCTrackMomFit.$(SRC_EXT) \
            CsRCOptCorr.$(SRC_EXT) \
	    cforOpen.$(SRC_EXT)


F77_SRCS = f-digits.$(F77_EXT) \
	   writeapp.$(F77_EXT) \
	   writebuff.$(F77_EXT) \
           readbuff.$(F77_EXT) \
           openfile.$(F77_EXT)

# Tell to general which extra libs.... and remove them from general...

# General... do not remove...

include $(top_srcdir)/makefiles/General.mk

