      real dcell
      parameter (dcell=38.3)
      
      integer mem
      parameter (mem=500000)
      
      integer numc
      parameter (numc=3072)

      integer numcl
      parameter (numcl=500)

      integer numg
      parameter (numg=200)

      integer numgcl
      parameter (numgcl=50)

      integer numgcl3
      parameter (numgcl3=150)

      integer numgcls
      parameter (numgcls=2500)

      real pi2
      parameter (pi2=6.2831853072)

