top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=CsMag

SCHEMA_DDL = CsPersFieldSM1.ddl\
             CsPersFieldSM2.ddl\
             CsPersFieldSol.ddl

APPL_SRCS = CsFieldGridSol.$(SRC_EXT)\
	    CsFieldGridSM1.$(SRC_EXT)\
	    CsPersFieldSol.$(SRC_EXT)\
	    CsPersFieldSM1.$(SRC_EXT)\
	    CsPersFieldSM2.$(SRC_EXT)\
	    CsPersFieldSol_ddl.$(SRC_EXT)\
	    CsPersFieldSM1_ddl.$(SRC_EXT)\
	    CsPersFieldSM2_ddl.$(SRC_EXT)\
	    CsMagDbUpdater.$(SRC_EXT)\
	    CsMagDbReader.$(SRC_EXT)\
            CsMagFieldSol.$(SRC_EXT)\
            CsMagFieldSM1.$(SRC_EXT)

include $(top_srcdir)/makefiles/General.mk
