
//                            dR   dphi(H)  dtheta(V)

RICHONE   MT28   [ 0 - 2 ]     3.    0.0      0.0
RICHONE   MT27   [ 0 - 2 ]    10.    0.11    -0.19
RICHONE   MT26   [ 0 - 2 ]    10.   -0.05    -0.36
RICHONE   MT25   [ 0 - 2 ]    13.   -0.00    -0.29
RICHONE   MT53   [ 0 - 2 ]     6.    0.17    -0.66
RICHONE   MT54   [ 0 - 2 ]    -1.    0.12    -1.24
RICHONE   MT55   [ 0 - 2 ]     5.    0.12    -0.76
RICHONE   MT56   [ 0 - 2 ]    17.    0.0      0.0

RICHONE   MT22   [ 0 - 2 ]    16.    0.0      0.0
RICHONE   MT21   [ 0 - 2 ]    10.    0.16     0.74
RICHONE   MT20   [ 0 - 2 ]    10.    0.27     0.33
RICHONE   MT19   [ 0 - 2 ]     6.    0.04     0.10
RICHONE   MT48   [ 0 - 2 ]     7.    0.33     0.03
RICHONE   MT49   [ 0 - 2 ]    12.    0.19     0.52
RICHONE   MT50   [ 0 - 2 ]    18.    0.0      0.0

RICHONE   MT3    [ 0 - 2 ]    19.    0.0      0.0
RICHONE   MT2    [ 0 - 2 ]    11.    0.67     1.19
RICHONE   MT1    [ 0 - 2 ]     7.    0.40     0.06
RICHONE   MT31   [ 0 - 2 ]     7.    0.10     0.42
RICHONE   MT32   [ 0 - 2 ]    12.   -0.11     0.93
RICHONE   MT33   [ 0 - 2 ]    17.    0.0      0.0

