
//                            dR   dphi(H)  dtheta(V)

RICHONE   MB16   [ 0 - 2 ]    -5.    0.10    -0.86
RICHONE   MB15   [ 0 - 2 ]     4.    0.37    -1.05
RICHONE   MB14   [ 0 - 2 ]    -8.    0.52    -1.22
RICHONE   MB13   [ 0 - 2 ]    -6.    0.25    -1.13
RICHONE   MB42   [ 0 - 2 ]     3.   -0.46    -1.04
RICHONE   MB43   [ 0 - 2 ]   -10.   -0.53    -0.57
RICHONE   MB44   [ 0 - 2 ]     6.   -0.59    -0.17
RICHONE   MB45   [ 0 - 2 ]    -7.   -0.42     0.03

RICHONE   MB10   [ 0 - 2 ]    -8.   -0.15    -1.17
RICHONE   MB9    [ 0 - 2 ]    -2.    0.31    -1.63
RICHONE   MB8    [ 0 - 2 ]    -2.    0.34    -1.40
RICHONE   MB7    [ 0 - 2 ]     0.    0.12    -1.22
RICHONE   MB37   [ 0 - 2 ]     0.   -0.19    -0.73
RICHONE   MB38   [ 0 - 2 ]     3.   -0.39    -0.43
RICHONE   MB39   [ 0 - 2 ]     2.   -0.54     0.04

RICHONE   MB3    [ 0 - 2 ]    -3.    0.37    -1.23
RICHONE   MB2    [ 0 - 2 ]    -2.    0.11    -1.47
RICHONE   MB1    [ 0 - 2 ]     1.    0.61    -1.38
RICHONE   MB31   [ 0 - 2 ]     3.    0.45    -1.14
RICHONE   MB32   [ 0 - 2 ]     4.    0.09    -0.52
RICHONE   MB33   [ 0 - 2 ]     3.    0.06     0.03

