
//                            dR   dphi(H)  dtheta(V)

RICHONE   MT28   [ 0 - 2 ]     3.    0.0      0.0
RICHONE   MT27   [ 0 - 2 ]    10.    0.0      0.0
RICHONE   MT26   [ 0 - 2 ]    10.    0.0      0.0
RICHONE   MT25   [ 0 - 2 ]    13.    0.0      0.0
RICHONE   MT53   [ 0 - 2 ]     6.    0.0      0.0
RICHONE   MT54   [ 0 - 2 ]    -1.    0.0      0.0
RICHONE   MT55   [ 0 - 2 ]     5.    0.0      0.0
RICHONE   MT56   [ 0 - 2 ]    17.    0.0      0.0

RICHONE   MT22   [ 0 - 2 ]    16.    0.0      0.0
RICHONE   MT21   [ 0 - 2 ]    10.    0.0      0.0
RICHONE   MT20   [ 0 - 2 ]    10.    0.0      0.0
RICHONE   MT19   [ 0 - 2 ]     6.    0.0      0.0
RICHONE   MT48   [ 0 - 2 ]     7.    0.0      0.0
RICHONE   MT49   [ 0 - 2 ]    12.    0.0      0.0
RICHONE   MT50   [ 0 - 2 ]    18.    0.0      0.0

RICHONE   MT3    [ 0 - 2 ]    19.    0.0      0.0
RICHONE   MT2    [ 0 - 2 ]    11.    0.0      0.0
RICHONE   MT1    [ 0 - 2 ]     7.    0.0      0.0
RICHONE   MT31   [ 0 - 2 ]     7.    0.0      0.0
RICHONE   MT32   [ 0 - 2 ]    12.    0.0      0.0
RICHONE   MT33   [ 0 - 2 ]    17.    0.0      0.0

