
//                            dR   dphi(H)  dtheta(V)

RICHONE   MB16   [ 0 - 2 ]    -5.    0.0     0.0
RICHONE   MB15   [ 0 - 2 ]     4.    0.04   -0.54
RICHONE   MB14   [ 0 - 2 ]    -8.   -0.29    0.79
RICHONE   MB13   [ 0 - 2 ]    -6.   -0.13    0.32
RICHONE   MB42   [ 0 - 2 ]     3.    0.10   -0.17
RICHONE   MB43   [ 0 - 2 ]   -10.    0.44    0.44
RICHONE   MB44   [ 0 - 2 ]     6.    0.22   -1.39
RICHONE   MB45   [ 0 - 2 ]    -7.    0.0     0.0

RICHONE   MB10   [ 0 - 2 ]    -8.    0.0     0.0
RICHONE   MB9    [ 0 - 2 ]    -2.   -0.13    0.38
RICHONE   MB8    [ 0 - 2 ]    -2.   -0.32    0.07
RICHONE   MB7    [ 0 - 2 ]     0.   -0.13   -0.15
RICHONE   MB37   [ 0 - 2 ]     0.    0.09   -0.58
RICHONE   MB38   [ 0 - 2 ]     3.    0.41   -1.08
RICHONE   MB39   [ 0 - 2 ]     2.    0.0     0.0

RICHONE   MB3    [ 0 - 2 ]    -3.    0.0     0.0
RICHONE   MB2    [ 0 - 2 ]    -2.    0.03    0.13
RICHONE   MB1    [ 0 - 2 ]     1.   -0.28   -0.13
RICHONE   MB31   [ 0 - 2 ]     3.   -0.37   -0.29
RICHONE   MB32   [ 0 - 2 ]     4.   -0.02   -0.91
RICHONE   MB33   [ 0 - 2 ]     3.    0.0     0.0

