
//                            dR   dphi(H)  dtheta(V)

RICHONE   MT28   [ 0 - 2 ]     3.    0.65    -0.39
RICHONE   MT27   [ 0 - 2 ]    10.    0.80    -0.01
RICHONE   MT26   [ 0 - 2 ]    10.    0.67     0.04
RICHONE   MT25   [ 0 - 2 ]    13.    0.0      0.0
RICHONE   MT53   [ 0 - 2 ]     6.    0.0      0.0
RICHONE   MT54   [ 0 - 2 ]    -1.    0.19     0.25
RICHONE   MT55   [ 0 - 2 ]     5.   -0.04     0.16
RICHONE   MT56   [ 0 - 2 ]    17.   -0.58     0.20

RICHONE   MT22   [ 0 - 2 ]    16.    0.90    -0.50
RICHONE   MT21   [ 0 - 2 ]    10.    0.75    -0.43
RICHONE   MT20   [ 0 - 2 ]    10.    0.23    -0.08
RICHONE   MT19   [ 0 - 2 ]     6.    0.0      0.0
RICHONE   MT48   [ 0 - 2 ]     7.    0.01    -0.17
RICHONE   MT49   [ 0 - 2 ]    12.    0.10     0.04
RICHONE   MT50   [ 0 - 2 ]    18.   -0.68    -0.08

RICHONE   MT3    [ 0 - 2 ]    19.    0.59    -0.63
RICHONE   MT2    [ 0 - 2 ]    11.   -0.01    -0.39
RICHONE   MT1    [ 0 - 2 ]     7.    0.0      0.0
RICHONE   MT31   [ 0 - 2 ]     7.    0.0      0.0
RICHONE   MT32   [ 0 - 2 ]    12.    0.22    -0.13
RICHONE   MT33   [ 0 - 2 ]    17.   -0.16     0.04

