
//                            dR   dphi(H)  dtheta(V)

RICHONE   MB16   [ 0 - 2 ]    -5.    0.0     0.0
RICHONE   MB15   [ 0 - 2 ]     4.    0.0     0.0
RICHONE   MB14   [ 0 - 2 ]    -8.    0.0     0.0
RICHONE   MB13   [ 0 - 2 ]    -6.    0.0     0.0
RICHONE   MB42   [ 0 - 2 ]     3.    0.0     0.0
RICHONE   MB43   [ 0 - 2 ]   -10.    0.0     0.0
RICHONE   MB44   [ 0 - 2 ]     6.    0.0     0.0
RICHONE   MB45   [ 0 - 2 ]    -7.    0.0     0.0

RICHONE   MB10   [ 0 - 2 ]    -8.    0.0     0.0
RICHONE   MB9    [ 0 - 2 ]    -2.    0.0     0.0
RICHONE   MB8    [ 0 - 2 ]    -2.    0.0     0.0
RICHONE   MB7    [ 0 - 2 ]     0.    0.0     0.0
RICHONE   MB37   [ 0 - 2 ]     0.    0.0     0.0
RICHONE   MB38   [ 0 - 2 ]     3.    0.0     0.0
RICHONE   MB39   [ 0 - 2 ]     2.    0.0     0.0

RICHONE   MB3    [ 0 - 2 ]    -3.    0.0     0.0
RICHONE   MB2    [ 0 - 2 ]    -2.    0.0     0.0
RICHONE   MB1    [ 0 - 2 ]     1.    0.0     0.0
RICHONE   MB31   [ 0 - 2 ]     3.    0.0     0.0
RICHONE   MB32   [ 0 - 2 ]     4.    0.0     0.0
RICHONE   MB33   [ 0 - 2 ]     3.    0.0     0.0

