top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=VrtRoland

APPL_SRCS = Roland.$(SRC_EXT)           \
            CsRolandPattern.$(SRC_EXT)  \
	    doPattern.$(SRC_EXT)        \
            getPatterns.$(SRC_EXT)
	    
include $(top_srcdir)/makefiles/General.mk
	    
FDIRS=.