top_srcdir = ../../..
include $(top_srcdir)/makefiles/Include.mk

LIBRARY=Sample
TEST_PROGRAMS=

APPL_SRCS = CsSamplePrepattern.$(SRC_EXT) \
	    CsSampleBridging.$(SRC_EXT) \
	    CsSampleFitting.$(SRC_EXT) 

include $(top_srcdir)/makefiles/General.mk

